name: check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: install-ubuntu
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: install-windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Setup MSVC
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: moon version & update
        run: |
          moon version --all
          moon update

      - name: moon check (library)
        run: |
          moon -C lib install
          moon -C lib check --target native,all

      - name: moon lint (library)
        continue-on-error: true
        run: |
          moon -C lib fmt && git diff --exit-code
          moon -C lib info && git diff --exit-code

      - name: moon check (plugin)
        run: |
          moon -C plugin install
          moon -C plugin check --target native

      - name: moon lint (plugin)
        continue-on-error: true
        run: |
          moon -C plugin fmt && git diff --exit-code
          moon -C plugin info && git diff --exit-code

      - name: moon check (cli)
        run: |
          moon -C cli install
          moon -C cli check --target native

      - name: moon lint (cli)
        continue-on-error: true
        run: |
          moon -C cli fmt && git diff --exit-code
          moon -C cli info --target native && git diff --exit-code
